
  trivy-sca:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Scan (Fail on High/Critical)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          severity: CRITICAL,HIGH
          exit-code: 1
